import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#8E9B95",
        "outline-variant": "#354349",
        surface: "#0F171B",
        "surface-dim": "#0c1418",
        "surface-bright": "#323a3f",
        "surface-container-lowest": "#070f13",
        "surface-container-low": "#151d21",
        "surface-container": "#192125",
        "surface-container-high": "#232b2f",
        "surface-container-highest": "#2e363a",
        "surface-variant": "#2e363a",
        "surface-tint": "#9cd2b4",
        "on-surface": "#F4F3EE",
        "on-surface-variant": "#C0C7C3",
        "inverse-surface": "#F4F3EE",
        "inverse-on-surface": "#293236",
        background: "#0F171B",
        "on-background": "#F4F3EE",
        primary: "#aae1c2",
        "primary-container": "#8fc5a7",
        "primary-fixed": "#b7efcf",
        "primary-fixed-dim": "#9cd2b4",
        "on-primary": "#09120E",
        "on-primary-container": "#09120E",
        "on-primary-fixed": "#09120E",
        "on-primary-fixed-variant": "#14281E",
        "inverse-primary": "#35684f",
        secondary: "#a5d0b7",
        "secondary-container": "#1A3B2B",
        "secondary-fixed": "#c1edd2",
        "secondary-fixed-dim": "#a5d0b7",
        "on-secondary": "#09120E",
        "on-secondary-container": "#B6ECCF",
        "on-secondary-fixed": "#09120E",
        "on-secondary-fixed-variant": "#1B3B2B",
        tertiary: "#efd28e",
        "tertiary-container": "#d2b675",
        "tertiary-fixed": "#fedf9b",
        "tertiary-fixed-dim": "#e0c381",
        "on-tertiary": "#261c00",
        "on-tertiary-container": "#3d2e05",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#58440e",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "space-4xl": "3.5rem",
        "sidebar-width": "260px",
        gutter: "1.25rem",
        "card-padding": "1.25rem",
      },
      fontFamily: {
        sans: ["var(--font-primary)", "Manrope", "sans-serif"],
        display: ["var(--font-display)", "DM Sans", "sans-serif"],
        serif: ["var(--font-serif)", "Newsreader", "serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "headline-sm": ["var(--font-primary)", "Manrope"],
        "headline-md": ["var(--font-display)", "DM Sans"],
        "headline-lg": ["var(--font-display)", "DM Sans"],
        "display-hero": ["var(--font-display)", "DM Sans"],
        "display-quote": ["var(--font-serif)", "Newsreader", "serif"],
        "body-sm": ["var(--font-primary)", "Manrope"],
        "body-md": ["var(--font-primary)", "Manrope"],
        "body-lg": ["var(--font-primary)", "Manrope"],
        "label-mono-wide": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-tag": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "button-text": ["var(--font-primary)", "Manrope"],
      },
      letterSpacing: {
        "tightest-hero": "-0.045em",
        "tighter-hero": "-0.035em",
        heading: "-0.025em",
      },
      fontSize: {
        "label-tag": ["10px", { lineHeight: "14px", letterSpacing: "0.15em", fontWeight: "600" }],
        "label-mono-wide": ["11px", { lineHeight: "16px", letterSpacing: "0.2em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "button-text": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "650" }],
        "headline-sm": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["clamp(1.75rem, 3.5vw, 2.75rem)", { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-quote": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "display-hero": ["clamp(2.4rem, 5.5vw, 4.75rem)", { lineHeight: "1.02", letterSpacing: "-0.04em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
