import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Nivora Core Design System Mapped to CSS Variables with RGB Alpha Support
        outline: "rgb(var(--outline-rgb, 142 141 138) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb, 216 195 165) / <alpha-value>)",
        surface: "rgb(var(--surface-rgb, 248 246 240) / <alpha-value>)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "rgb(var(--surface-lowest-rgb, 234 231 220) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-low-rgb, 243 239 230) / <alpha-value>)",
        "surface-container": "rgb(var(--surface-container-rgb, 250 248 243) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-high-rgb, 234 229 217) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--surface-highest-rgb, 221 215 201) / <alpha-value>)",
        "surface-variant": "var(--surface-variant)",
        "surface-tint": "#E98074",
        "on-surface": "rgb(var(--on-surface-rgb, 38 34 32) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant-rgb, 110 107 103) / <alpha-value>)",
        "inverse-surface": "var(--inverse-surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        background: "rgb(var(--background-rgb, 234 231 220) / <alpha-value>)",
        "on-background": "rgb(var(--on-surface-rgb, 38 34 32) / <alpha-value>)",

        // Primary: Deep Coral (#E85A4F) for Primary CTAs, active states, key interactive elements
        primary: "rgb(var(--primary-rgb, 232 90 79) / <alpha-value>)",
        "primary-container": "var(--primary-container)",
        "primary-fixed": "#E85A4F",
        "primary-fixed-dim": "#E98074",
        "on-primary": "var(--on-primary)",
        "on-primary-container": "var(--on-primary-container)",
        "on-primary-fixed": "#FFFFFF",
        "on-primary-fixed-variant": "#FFFFFF",
        "inverse-primary": "#FFB4AB",

        // Secondary: Muted Sand (#D8C3A5) for selected navigation, subtle sections, decorative
        secondary: "rgb(var(--secondary-rgb, 216 195 165) / <alpha-value>)",
        "secondary-container": "rgb(var(--secondary-container-rgb, 216 195 165) / <alpha-value>)",
        "secondary-fixed": "#E6D7C3",
        "secondary-fixed-dim": "#D8C3A5",
        "on-secondary": "var(--on-secondary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",

        // Tertiary: Warm Gray (#8E8D8A)
        tertiary: "rgb(var(--tertiary-rgb, 142 141 138) / <alpha-value>)",
        "tertiary-container": "var(--tertiary-container)",
        "tertiary-fixed": "#D8C3A5",
        "tertiary-fixed-dim": "#8E8D8A",
        "on-tertiary": "var(--on-tertiary)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",

        // Semantic Alerts & Errors: Deep Coral derived
        error: "rgb(var(--error-rgb, 232 90 79) / <alpha-value>)",
        "error-container": "var(--error-container)",
        "on-error": "var(--on-error)",
        "on-error-container": "var(--on-error-container)",

        // Centralized Nivora Design Tokens
        nivora: {
          bg: "var(--nivora-bg)",
          surface: "var(--nivora-surface)",
          "surface-secondary": "var(--nivora-surface-secondary)",
          text: "var(--nivora-text)",
          "text-muted": "var(--nivora-text-muted)",
          border: "var(--nivora-border)",
          accent: "var(--nivora-accent)",
          "accent-strong": "var(--nivora-accent-strong)",
          "accent-soft": "var(--nivora-accent-soft)",
        },

        // Exact Visual Direction Primary Palette Access
        "warm-ivory": "#EAE7DC",
        "muted-sand": "#D8C3A5",
        "warm-gray": "#8E8D8A",
        coral: "#E98074",
        "deep-coral": "#E85A4F",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "space-4xl": "3.5rem",
        "sidebar-width": "260px",
        gutter: "1.25rem",
        "card-padding": "1.25rem",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "var(--font-primary)", "Manrope", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        primary: ["var(--font-manrope)", "var(--font-primary)", "Manrope", "sans-serif"],
        display: ["var(--font-instrument-serif)", "var(--font-display)", "'Instrument Serif'", "Georgia", "serif"],
        serif: ["var(--font-instrument-serif)", "var(--font-serif)", "'Instrument Serif'", "Georgia", "serif"],
        editorial: ["var(--font-instrument-serif)", "var(--font-display)", "'Instrument Serif'", "Georgia", "serif"],
        mono: ["var(--font-manrope)", "var(--font-primary)", "Manrope", "sans-serif"],
        code: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "headline-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "display-hero": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "display-quote": ["var(--font-instrument-serif)", "'Instrument Serif'", "Georgia", "serif"],
        "body-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-mono-wide": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-tag": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "button-text": ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      letterSpacing: {
        "tightest-hero": "-0.045em",
        "tighter-hero": "-0.035em",
        heading: "-0.025em",
      },
      fontSize: {
        "label-tag": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-mono-wide": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "button-text": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["clamp(1.25rem, 2.2vw, 1.5rem)", { lineHeight: "1.25", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["clamp(1.75rem, 3.5vw, 2.5rem)", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-quote": ["clamp(1.15rem, 2vw, 1.4rem)", { lineHeight: "1.4", fontWeight: "400" }],
        "display-hero": ["clamp(2.4rem, 5vw, 4.25rem)", { lineHeight: "1.02", letterSpacing: "-0.035em", fontWeight: "800" }],
        "editorial-hero": ["clamp(2.75rem, 6.5vw, 5.5rem)", { lineHeight: "0.98", letterSpacing: "-0.02em", fontWeight: "400" }],
        "editorial-heading": ["clamp(2rem, 4.5vw, 3.5rem)", { lineHeight: "1.08", letterSpacing: "-0.015em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
