import { ClubProvider, NormalizedEventOrClub } from '../types';

/**
 * Curated provider of real, verified, globally recognized student clubs and university technical chapters.
 * IMPORTANT: All URLs point to verified official public community directories. Zero fake clubs.
 */
export class RealClubProvider implements ClubProvider {
  name = 'Collegiate Technical Chapters';

  async fetchClubs(): Promise<NormalizedEventOrClub[]> {
    const clubs: NormalizedEventOrClub[] = [
      {
        id: 'club-gdg-campus',
        title: 'Google Developer Groups (GDG) on Campus',
        description: 'University student developer communities powered by Google Developers to learn Android, Web, Cloud, and Machine Learning through hands-on workshops and hackathons.',
        type: 'club',
        category: 'Technical Events',
        organizer: 'Google for Developers',
        image_url: 'https://developers.google.com/static/community/images/gdg-logo.svg',
        location: 'Delhi NCR & Pan-India',
        is_online: false,
        source_name: 'GDG Community',
        source_url: 'https://gdg.community.dev',
        registration_url: 'https://gdg.community.dev',
        tags: ['Google Cloud', 'Android', 'Web Dev', 'AI & ML'],
        member_count: '1,500+ active chapters',
      },
      {
        id: 'club-acm-student',
        title: 'ACM Student Chapter',
        description: 'The premier collegiate computing society advancing computer science as a science and profession through algorithm sprints, research reading groups, and hackathons.',
        type: 'club',
        category: 'Technical Events',
        organizer: 'Association for Computing Machinery',
        image_url: 'https://www.acm.org/sites/default/files/acm-logo.png',
        location: 'University Chapters Worldwide',
        is_online: false,
        source_name: 'ACM Global',
        source_url: 'https://www.acm.org/chapters/students',
        registration_url: 'https://www.acm.org/chapters/students',
        tags: ['Algorithms', 'Systems', 'Research', 'Competitive Programming'],
        member_count: '800+ student chapters',
      },
      {
        id: 'club-ieee-student',
        title: 'IEEE Student Branch',
        description: 'Global engineering and technology network offering students access to technical publications, robotics hardware hackathons, and IEEE computer society mentoring.',
        type: 'club',
        category: 'Technical Events',
        organizer: 'IEEE (Institute of Electrical and Electronics Engineers)',
        location: 'Delhi Section & Global',
        is_online: false,
        source_name: 'IEEE Global',
        source_url: 'https://www.ieee.org/membership/students/index.html',
        registration_url: 'https://www.ieee.org/membership/students/index.html',
        tags: ['Hardware', 'Robotics', 'IoT', 'Electrical & Computing'],
        member_count: '120k+ student members',
      },
      {
        id: 'club-aws-cloud',
        title: 'AWS Cloud Clubs',
        description: 'Official student-led cloud builder communities sponsored by AWS to help university students master AWS services, cloud certifications, and serverless architectures.',
        type: 'club',
        category: 'Workshops',
        organizer: 'Amazon Web Services',
        location: 'University Chapters',
        is_online: false,
        source_name: 'AWS Developer Community',
        source_url: 'https://aws.amazon.com/developer/community/students/cloud-clubs/',
        registration_url: 'https://aws.amazon.com/developer/community/students/cloud-clubs/',
        tags: ['Cloud Architecture', 'AWS', 'DevOps', 'Certifications'],
        member_count: '300+ university clubs',
      },
      {
        id: 'club-mlsa',
        title: 'Microsoft Learn Student Ambassadors (MLSA)',
        description: 'Campus student leaders who host technical workshops on Azure, AI, and GitHub to help batchmates gain job-ready software engineering skills.',
        type: 'club',
        category: 'Workshops',
        organizer: 'Microsoft',
        location: 'Global Student Network',
        is_online: true,
        source_name: 'Microsoft Learn',
        source_url: 'https://studentambassadors.microsoft.com',
        registration_url: 'https://studentambassadors.microsoft.com',
        tags: ['Azure', 'AI', 'Cloud', 'Leadership'],
        member_count: '4,000+ ambassadors',
      },
      {
        id: 'club-gfg-student',
        title: 'GeeksforGeeks Student Chapters',
        description: 'Student-run university programming chapters focusing on Data Structures & Algorithms, coding contests, technical placement preparation, and web development.',
        type: 'club',
        category: 'Competitions',
        organizer: 'GeeksforGeeks',
        location: 'Indian College Campuses',
        is_online: false,
        source_name: 'GeeksforGeeks',
        source_url: 'https://www.geeksforgeeks.org/geeksforgeeks-student-chapters/',
        registration_url: 'https://www.geeksforgeeks.org/geeksforgeeks-student-chapters/',
        tags: ['DSA', 'Competitive Programming', 'Interview Prep', 'Contests'],
        member_count: '500+ Indian campuses',
      },
      {
        id: 'club-mlh',
        title: 'Major League Hacking (MLH)',
        description: 'The official student hackathon league powering collegiate hackathons, weekend sprints, open source fellowships, and developer community building worldwide.',
        type: 'club',
        category: 'Hackathons',
        organizer: 'Major League Hacking',
        location: 'Global Hackathon League',
        is_online: true,
        source_name: 'MLH Official',
        source_url: 'https://mlh.io',
        registration_url: 'https://mlh.io',
        tags: ['Hackathons', 'Student League', 'Open Source', 'Fellowships'],
        member_count: '100k+ annual hackers',
      },
      {
        id: 'club-github-campus',
        title: 'GitHub Campus Program & Experts',
        description: 'Student technical communities trained by GitHub to run open-source hackathons, teach Git workflows, and foster developer collaboration on campus.',
        type: 'club',
        category: 'Other',
        organizer: 'GitHub Education',
        location: 'Global Campus Network',
        is_online: true,
        source_name: 'GitHub Education',
        source_url: 'https://education.github.com',
        registration_url: 'https://education.github.com',
        tags: ['Git', 'Open Source', 'Campus Experts', 'Developer Tools'],
        member_count: 'Campus Global Network',
      },
    ];

    return clubs;
  }
}
